---
title: "Bil code"
author: "Thomas Holm-Weber"
date: "2023-03-28"
output: html_document
---
No echo
```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Packages
```{r, echo=FALSE}
install.packages("tidyverse", repos = "http://cran.us.r-project.org")
library(tidyverse)
library(ggplot2)
```


Data Import Mac
```{r, echo=FALSE}
getwd()
setwd("/Users/thomasholm-weber/Desktop/bil/bil2/data")
bil = read_csv("bil.csv")
```


Table 1 data
```{r, echo=FALSE}
mean(bil$age_at_doi, na.rm = T)
mean(bil$bp_sys_mean, na.rm = T)
mean(bil$bp_dia_mean, na.rm = T)
mean(bil$hr_mean, na.rm = T)

glimpse(bil$bp_mean_dia)
```

Subsets disease
```{r, echo=FALSE}
bil$disease = recode(bil$disease, "1" = "ba", "2" = "tof")

ba = bil %>% filter(disease=="ba")
tof = bil %>% filter(disease=="tof")
```

ToF table1
```{r, echo=FALSE}
mean(tof$age_at_doi, na.rm = T)
mean(tof$bp_sys_mean, na.rm = T)
mean(tof$bp_dia_mean, na.rm = T)
mean(tof$hr_mean, na.rm = T)
```


BA table1
```{r, echo=FALSE}
mean(ba$age_at_doi, na.rm = T)
mean(ba$bp_sys_mean, na.rm = T)
mean(ba$bp_dia_mean, na.rm = T)
mean(ba$hr_mean, na.rm = T)
```



NIRF ToF
```{r, echo=FALSE}
mean(tof$lrate, na.rm = T)
mean(tof$lrate_2, na.rm = T)
mean(tof$lpressure, na.rm = T)
```

NIRF BA
```{r, echo=FALSE}
mean(ba$lrate, na.rm = T)
mean(ba$lrate_2, na.rm = T)
mean(ba$lpressure, na.rm = T)
```

MR ToF
```{r, echo=FALSE}
mean(tof$mritype_t, na.rm = T)
```

MR BA
```{r, echo=FALSE}
mean(ba$mritype_t, na.rm = T)
```

Boxplot LP
```{r, echo=FALSE}
ggplot(bil, aes(x = disease, y = lpressure)) +
  geom_boxplot() +
  labs(x = "disease", y = "lpressure")

```


Boxplot LR
```{r, echo=FALSE}
ggplot(bil, aes(x = disease, y = lrate)) +
  geom_boxplot() +
  labs(x = "disease", y = "lrate")

```


Boxplot LR2
```{r, echo=FALSE}
ggplot(bil, aes(x = disease, y = lrate_2)) +
  geom_boxplot() +
  labs(x = "disease", y = "lrate2")

```